# -*- coding: utf-8 -*-
"""ast2proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fR_PNJ7N1QHYvCro_FTNgpWZViU4BGkO
"""

import pandas as pd
import matplotlib.pyplot as plt

filename = open('student_042.txt')
data = pd.read_csv(filename, sep =' ', header=None).values
plt.title('Light Curve')
plt.xlabel('Time (sec)')
plt.ylabel('Relative Brightness') 
x = data[:,0]
y = data[:,1]
plt.plot(x,y,'-')
plt.show()



"""# New Section"""

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

fig = plt.figure()
ax = fig.add_subplot(111)
filename = open('student_042.txt')
plt.plot(x[2:27], y[2:27], linewidth=0.5)
data = pd.read_csv(filename, sep =' ', header=None).values

plt.title('West Linecurve')
plt.xlabel('Time (s)')
plt.ylabel('Relative Brightness')
print("Standard Deviation:", np.std(y))
print("Average:", np.average(y))

import pandas as pd 
import numpy as np
import math
import matplotlib.pyplot as plt 

fig = plt.figure()
ax = fig.add_subplot(111)
filename = open('student_042.txt')
data = pd.read_csv(filename, sep =' ', header=None).values
x = data[:,0]
y = data[:,1]

plt.plot(x[2:27], y[2:27], linewidth=0.5, color="green")
plt.plot(x[2:27], y[20752:20777], linewidth=0.5, color="orange")
#plt.plot(x[2:27], y[20752:20777], linewidth=0.5, color="purple")
#plt.plot(x[2:27], y[40752:40777], linewidth=0.5, color="red")
#plt.plot(x[2:27], y[60752:60777], linewidth=0.5, color="blue")
period = x[27:10777]

secs = sum(period)
days = secs/(60*60*24)
print('Orbital Period:', secs, 'seconds, ', days, 'days')
avg = np.average(x[0:27])
radius = (113503.42)*(math.sqrt(1-np.average(y)))
print('Radius:', radius, '+- 0.0056 Earth Radii')

plt.title('West Light Curve')
plt.xlabel('Time (s)')
plt.ylabel('Relative Brightness')